export const COMPARE_PLANS = Object.freeze([
  {
    id: "guest",
    name: "Guest",
    badge: "No account",
    price: "Free",
    period: "No account required",
    account: "No account",
    catalog: "Live / Movies / Series: 5,000 each",
    watchTime: "Watch time: 3 hours/day",
    connections: "2 saved connections",
    sessions: "1 session",
    ads: "Ads included",
    sync: "No cloud sync",
    support: "Community support",
  },
  {
    id: "free",
    name: "Free",
    badge: "Basic account",
    price: "Free",
    period: "Free account required",
    account: "Free account",
    catalog: "Live / Movies / Series: 5,000 each",
    watchTime: "Watch time: 3 hours/day",
    connections: "2 saved connections",
    sessions: "1 session",
    ads: "Ads included",
    sync: "Cloud sync included",
    support: "Community support",
  },
  {
    id: "standard",
    name: "Standard",
    badge: "Available",
    price: "$2.99",
    period: "Standard access",
    pricingDetails: ["$2.99 30-day pass", "$2.85 monthly", "$29.99 yearly"],
    account: "Standard account",
    catalog: "Unlimited catalog: Live / Movies / Series",
    watchTime: "Unlimited watch time",
    connections: "5 connections",
    sessions: "3 sessions",
    ads: "No ads",
    sync: "Cloud sync included",
    support: "Billing/support included",
  },
  {
    id: "pro",
    name: "Pro",
    badge: "Coming soon",
    price: "Coming soon",
    period: "Not currently available",
    account: "Pro account",
    catalog: "Unlimited catalog",
    watchTime: "Unlimited watch time",
    connections: "10 connections",
    sessions: "5 sessions",
    ads: "No ads",
    sync: "Cloud sync included",
    support: "Priority billing/support",
  },
]);
